// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

