// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Object1 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Object1 = lv_calendar_create(ui_Screen3);
    lv_obj_t * ui_Object1_header = lv_calendar_add_header_arrow(ui_Object1);
    lv_obj_set_x(ui_Object1, -4);
    lv_obj_set_y(ui_Object1, -47);
    lv_obj_set_align(ui_Object1, LV_ALIGN_CENTER);

    ui_Button8 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_Button8, 52);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, -12);
    lv_obj_set_y(ui_Button8, 91);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "back");

    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Object1 = NULL;
    ui_Button8 = NULL;
    ui_Label11 = NULL;

}
