// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"
#include "../wifi_config.h"
#include "../protocol_parser.h"
#include "usart2.h"
#include <string.h>

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label8 = NULL;
static lv_obj_t * wifi_status_label = NULL;  /* WiFi 连接状态 */
// event funtions
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea2);
    }
}

/* ---- 定时检查 WiFi 配置结果 ---- */
static lv_timer_t *wifi_status_timer = NULL;

static void wifi_status_timer_cb(lv_timer_t *timer)
{
    int result = protocol_get_wifi_cfg_result();

    if (result == 0) return;  /* 还没收到回复，继续等待 */

    if (!wifi_status_label) {
        lv_timer_del(timer);
        wifi_status_timer = NULL;
        return;
    }

    if (result == 1) {
        lv_label_set_text(wifi_status_label, "Connected!");
        lv_obj_set_style_text_color(wifi_status_label,
            lv_color_hex(0x4CAF50), LV_PART_MAIN);  /* 绿色 */
    } else {
        lv_label_set_text(wifi_status_label, "Failed!");
        lv_obj_set_style_text_color(wifi_status_label,
            lv_color_hex(0xFF0000), LV_PART_MAIN);  /* 红色 */
    }

    lv_timer_del(timer);
    wifi_status_timer = NULL;
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        const char *ssid = lv_textarea_get_text(ui_TextArea1);
        const char *pwd  = lv_textarea_get_text(ui_TextArea2);

        /* 校验非空 */
        if (!ssid || strlen(ssid) == 0) {
            if (wifi_status_label) {
                lv_label_set_text(wifi_status_label, "SSID empty!");
                lv_obj_set_style_text_color(wifi_status_label,
                    lv_color_hex(0xFF0000), LV_PART_MAIN);
            }
            return;
        }

        /* 保存到 Flash */
        if (!wifi_config_save(ssid, pwd)) {
            if (wifi_status_label) {
                lv_label_set_text(wifi_status_label, "Save failed!");
                lv_obj_set_style_text_color(wifi_status_label,
                    lv_color_hex(0xFF0000), LV_PART_MAIN);
            }
            return;
        }

        /* 清除上次结果，准备接收新回复 */
        protocol_clear_wifi_cfg_result();

        /* 发送 WiFi 配置给 ESP32 */
        char buf[192];
        wifi_config_build_json(ssid, pwd, buf, sizeof(buf));
        USART2_SendString(buf);

        /* 状态反馈 */
        if (wifi_status_label) {
            lv_label_set_text(wifi_status_label, "Connecting...");
            lv_obj_set_style_text_color(wifi_status_label,
                lv_color_hex(0x2196F3), LV_PART_MAIN);  /* 蓝色 */
        }

        /* 启动定时器，每 500ms 检查 ESP32 的回复 */
        if (wifi_status_timer) {
            lv_timer_del(wifi_status_timer);
        }
        wifi_status_timer = lv_timer_create(wifi_status_timer_cb, 500, NULL);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Screen2);
    lv_obj_set_width(ui_Keyboard1, 237);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 98);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_TextArea1 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea1, 152);
    lv_obj_set_height(ui_TextArea1, 38);
    lv_obj_set_x(ui_TextArea1, 81);
    lv_obj_set_y(ui_TextArea1, 4);
    lv_obj_set_style_text_align(ui_TextArea1, LV_ALIGN_CENTER, 0);

    ui_TextArea2 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea2, 151);
    lv_obj_set_height(ui_TextArea2, 38);
    lv_obj_set_x(ui_TextArea2, 81);
    lv_obj_set_y(ui_TextArea2, 43);
    lv_obj_set_style_text_align(ui_TextArea2, LV_ALIGN_CENTER, 0);

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -74);
    lv_obj_set_y(ui_Label6, -137);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "ssid:");

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -81);
    lv_obj_set_y(ui_Label7, -98);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "password:");

    ui_Button5 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button5, 64);
    lv_obj_set_height(ui_Button5, 40);
    lv_obj_set_x(ui_Button5, 44);
    lv_obj_set_y(ui_Button5, -43);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 1);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "connect");

    ui_Button6 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button6, 62);
    lv_obj_set_height(ui_Button6, 39);
    lv_obj_set_x(ui_Button6, -61);
    lv_obj_set_y(ui_Button6, -44);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -1);
    lv_obj_set_y(ui_Label8, 1);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "back");

    /* ---- 密码输入框设置为密码模式 ---- */
    lv_textarea_set_password_mode(ui_TextArea2, true);

    /* ---- 预填已保存的 WiFi 凭据 ---- */
    char saved_ssid[33], saved_pwd[65];
    if (wifi_config_load(saved_ssid, sizeof(saved_ssid),
                         saved_pwd, sizeof(saved_pwd))) {
        lv_textarea_set_text(ui_TextArea1, saved_ssid);
        lv_textarea_set_text(ui_TextArea2, saved_pwd);
    }

    /* ---- WiFi 连接状态标签 ---- */
    wifi_status_label = lv_label_create(ui_Screen2);
    lv_obj_set_width(wifi_status_label, LV_SIZE_CONTENT);
    lv_obj_set_height(wifi_status_label, LV_SIZE_CONTENT);
    lv_obj_align(wifi_status_label, LV_ALIGN_BOTTOM_MID, 0, -8);
    lv_obj_set_style_text_color(wifi_status_label,
        lv_color_hex(0xAAAAAA), LV_PART_MAIN);
    lv_label_set_text(wifi_status_label, "");

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Keyboard1 = NULL;
    ui_TextArea1 = NULL;
    ui_TextArea2 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Button5 = NULL;
    ui_Label9 = NULL;
    ui_Button6 = NULL;
    ui_Label8 = NULL;
    wifi_status_label = NULL;

}
